### ISSUE TITLE
Disable anchor checks for snapcraft.io/docs URLs

### ISSUE THREAD

**Issue by farshidtz** [canonical/real-time-ubuntu-docs#69]
There are usually a few false positives as a result of this. Example:
`how-to/modify-kernel-boot-parameters.rst:166: [broken] https://snapcraft.io/docs/system-options#heading--kernel-dangerous-cmdline-append: Anchor 'heading--kernel-dangerous-cmdline-append' not found`

This should help: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_anchors_ignore_for_url

**Comment by AnneCYH** [comment]
Addressed here:

https://github.com/canonical/real-time-ubuntu-docs/pull/70
